development:
  adapter: postgresql
  database: unoriginal_raffler_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: unoriginal_raffler_test
  pool: 5
  timeout: 5000
  min_messages: WARNING

production:
  adapter: postgresql
  database: unoriginal_raffler_production
  pool: 5
  timeout: 5000
